apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-backend
  template:
    metadata:
      labels:
        app: myapp-backend
    spec:
      containers:
      - name: myapp-backend
        image: amirsh2023/myapp-backend:1.0.0  # Assuming you will also change the image name
        ports:
        - containerPort: 5000
